services:


  hikvision_event:
    build: 
      context: .  
    container_name: hikvision_event
    restart: always  
    ports:
      - "8786:8786"
    env_file:
      - .env

  # hikvision_event_dev:
  #   build: 
  #     context: . 
  #     filename: Dockerfile.dev 
  #   container_name: hikvision_event_dev
  #   restart: always  
  #   ports:
  #     - "8785:8785"
  #   env_file:
  #     - .env